#!/bin/sh -eu

# The contents of /dev can be recreated when needed.
rm -rfv "${1}"/dev/*

# debootstrap will copy these from the host. We remove them because it makes for
# a reproducibility issue.
rm -rfv "${1}"/etc/hostname
rm -rfv "${1}"/etc/resolv.conf

# A random ID generated that is a source of non-reproducibility.
rm -rfv "${1}"/etc/machine-id

# According to the Linux FHS, the /run directory is to be cleared each boot, so
# it should be fine to remove its contents:
#   https://refspecs.linuxfoundation.org/FHS_3.0/fhs/ch03s15.html
rm -rfv "${1}"/run/*

# According to the Linux FHS, the application must be able to regenerate or
# restore any data in the /var/cache directory, so it should be fine to
# remove its contents.
rm -rfv "${1}"/var/cache/*

# This is a file used by dpkg to know what packages are available. The local
# ./bootstrap script and debootstrap both generate basically the same file,
# but the ordering is different. They could be made the same with some
# effort, but this file is not actually essential and can be regenerated
# from the package list, so it should be good to remove here.
rm -rfv "${1}"/var/lib/dpkg/available

# This is a file that can be used by dpkg for backup purposes, but is
# generally not needed, especially on a just-bootstrapped system.
rm -rfv "${1}"/var/lib/dpkg/status-old

# These are log files that have timestamps which are a source of
# non-reproducibility.
rm -rfv "${1}"/var/log/bootstrap.log
rm -rfv "${1}"/var/log/dpkg.log
rm -rfv "${1}"/var/log/alternatives.log

# May appear sometimes.
rm -rfv "${1}"/etc/apparmor.d/local/sbin.dhclient

# Ensure some timestamps are updated.
touch "${1}"/usr/share
touch "${1}"/usr/share/doc
touch "${1}"/usr/share/locale
touch "${1}"/usr/share/man
touch "${1}"/usr/share/perl5
touch "${1}"/usr/lib/mime
touch "${1}"/usr/lib/systemd
touch "${1}"/usr/lib/terminfo
touch "${1}"/usr/share/bash-completion
touch "${1}"/usr/share/locale/*
touch "${1}"/usr/share/man/*
