name: debootstrap-jr
on:
  push:
    branches:
      - main
jobs:
  timestamp:
    runs-on: ubuntu-latest
    outputs:
      timestamp: ${{ steps.timestamp.outputs.timestamp }}
    steps:
      - name: Get Repository
        uses: actions/checkout@v4
      - name: Gather Timestamp
        id: timestamp
        run: |
          timestamp="$(git log -1 --format=tformat:%cd \
              --date=format:%Y-%m-%dT%H:%M:%SZ "${GITHUB_SHA}")"
          echo "Timestamp: ${timestamp}"
          echo "timestamp=${timestamp}" >> "${GITHUB_OUTPUT}"
          echo "${timestamp}" >> bootstrap-timestamp
      - name: Archive Bootstrap Timestamp
        uses: actions/upload-artifact@v4
        with:
          path: bootstrap-timestamp
          name: bootstrap-timestamp
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Get Repository
        uses: actions/checkout@v4
      - name: Run Lint
        run: |
          docker build . --target lint --tag lint
          docker run --rm --workdir /src --volume $(pwd):/src:ro lint make ci
  bootstrap:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        distribution:
          - bookworm
          - trixie
        architecture:
          - amd64
          - arm64
          - riscv64
        variant:
          - standard
          - buildd
          - minbase
        protocol:
          - http
          - https
        exclude:
          - distribution: bookworm
            architecture: riscv64
    needs:
      - timestamp
    env:
      timestamp: ${{ needs.timestamp.outputs.timestamp }}
      prefix: debian-${{ matrix.distribution }}-${{ matrix.architecture }}-${{ matrix.variant }}-${{ matrix.protocol }}
    steps:
      - name: Get Repository
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Run Bootstrap
        run: |
          docker build --target debootstrap-jr --tag debootstrap-jr .
          docker run \
            --env architecture=${{ matrix.architecture }} \
            --env distribution=${{ matrix.distribution }} \
            --env mirror=${{ matrix.protocol }}://deb.debian.org/debian \
            --env variant=${{ matrix.variant }} \
            --privileged \
            --volume "$(pwd)/cache:/cache" \
            --volume "$(pwd)/rootfs:/debian" \
            debootstrap-jr
          LC_ALL=C sudo tar --create --file ${prefix}-rootfs.tar \
            --directory rootfs --sort name --numeric-owner \
            --mtime "${timestamp}" --clamp-mtime .
          LC_ALL=C sudo tar --create --file ${prefix}-cache.tar \
            --directory cache --sort name --numeric-owner \
            --mtime "${timestamp}" --clamp-mtime .
          wget https://github.com/anchore/syft/releases/download/v1.16.0/syft_1.16.0_linux_amd64.tar.gz
          tar --extract --gzip --file syft*.tar.gz syft
          ./syft scan dir:rootfs \
            --base-path=rootfs \
            --source-name="${prefix}" \
            --source-version="${timestamp}" \
            -o "spdx-json=${prefix}-sbom.json"
      - name: Archive Root Filesystem
        uses: actions/upload-artifact@v4
        with:
          path: ${{ env.prefix }}-rootfs.tar
          name: ${{ env.prefix }}-rootfs.tar
      - name: Archive Cache
        uses: actions/upload-artifact@v4
        with:
          path: ${{ env.prefix }}-cache.tar
          name: ${{ env.prefix }}-cache.tar
      - name: Archive SBOM
        uses: actions/upload-artifact@v4
        with:
          path: ${{ env.prefix }}-sbom.json
          name: ${{ env.prefix }}-sbom.json
  bootstrap-offline:
    runs-on: ubuntu-latest
    needs:
      - timestamp
      - bootstrap
    strategy:
      fail-fast: false
      matrix:
        distribution:
          - bookworm
          - trixie
        architecture:
          - amd64
          - arm64
          - riscv64
        variant:
          - standard
          - buildd
          - minbase
        protocol:
          - http
          - https
        exclude:
          - distribution: bookworm
            architecture: riscv64
    env:
      timestamp: ${{ needs.timestamp.outputs.timestamp }}
      prefix: debian-${{ matrix.distribution }}-${{ matrix.architecture }}-${{ matrix.variant }}-${{ matrix.protocol }}
    steps:
      - name: Get Repository-
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Restore Cache
        uses: actions/download-artifact@v4
        with:
          name: ${{ env.prefix }}-cache.tar
      - name: Run Offline Bootstrap
        run: |
          mkdir cache
          sudo tar --extract --file ${prefix}-cache.tar --directory cache
          docker build --target debootstrap-jr --tag debootstrap-jr .
          docker run \
            --env architecture=${{ matrix.architecture }} \
            --env distribution=${{ matrix.distribution }} \
            --env keyserver=none \
            --env mirror=${{ matrix.protocol }}://deb.debian.org/debian \
            --env variant=${{ matrix.variant }} \
            --net none \
            --privileged \
            --volume "$(pwd)/cache:/cache:ro" \
            --volume "$(pwd)/rootfs:/debian" \
            debootstrap-jr
          timestamp="$(git log -1 --format=tformat:%cd \
            --date=format:%Y-%m-%dT%H:%M:%SZ "${GITHUB_SHA}")"
          LC_ALL=C sudo tar --create --file ${prefix}-offline.tar \
            --directory rootfs --sort name --numeric-owner \
            --mtime "${timestamp}" --clamp-mtime .
      - name: Get Original Bootstrap Rootfs
        uses: actions/download-artifact@v4
        with:
          name: ${{ env.prefix }}-rootfs.tar
      - name: Ensure Identical Artifacts
        run: |
          sha256sum ${prefix}-rootfs.tar ${prefix}-offline.tar
          if ! diff ${prefix}-rootfs.tar ${prefix}-offline.tar; then
            sudo apt-get update
            sudo apt-get install --yes diffoscope
            diffoscope ${prefix}-rootfs.tar ${prefix}-offline.tar
          fi
  debootstrap:
    runs-on: ubuntu-latest
    needs:
      - timestamp
      - bootstrap
    strategy:
      fail-fast: false
      matrix:
        distribution:
          - bookworm
          - trixie
        architecture:
          - amd64
          - arm64
          - riscv64
        variant:
          - standard
          - buildd
          - minbase
        protocol:
          - http
          - https
        exclude:
          - distribution: bookworm
            architecture: riscv64
    env:
      timestamp: ${{ needs.timestamp.outputs.timestamp }}
      prefix: debian-${{ matrix.distribution }}-${{ matrix.architecture }}-${{ matrix.variant }}-${{ matrix.protocol }}
    steps:
      - name: Get Repository
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Run debootstrap
        run: |
          docker build --target debootstrap --tag debootstrap .
          case "${{ matrix.variant }}" in
              standard)
                  docker run --privileged --volume "$(pwd):/out" debootstrap \
                      --arch ${{ matrix.architecture }} \
                      ${{ matrix.distribution }} /out/rootfs \
                      ${{ matrix.protocol }}://deb.debian.org/debian \
                  ;;
              buildd)
                  docker run --privileged --volume "$(pwd):/out" debootstrap \
                      --arch ${{ matrix.architecture }} \
                      --variant=buildd  \
                      --merged-usr \
                      ${{ matrix.distribution }} /out/rootfs \
                      ${{ matrix.protocol }}://deb.debian.org/debian \
                  ;;
              minbase)
                  docker run --privileged --volume "$(pwd):/out" debootstrap \
                      --arch ${{ matrix.architecture }} \
                      --variant=minbase \
                      ${{ matrix.distribution }} /out/rootfs \
                      ${{ matrix.protocol }}://deb.debian.org/debian \
                  ;;
              *)
                  echo "Bad variant."
                  exit 1
                  ;;
          esac
          sudo ./strip-debootstrap rootfs
          LC_ALL=C sudo tar --create --file ${prefix}-orig.tar \
            --directory rootfs --sort name --numeric-owner \
            --mtime "${timestamp}" --clamp-mtime .
      - name: Get Original Bootstrap Rootfs
        uses: actions/download-artifact@v4
        with:
          name: ${{ env.prefix }}-rootfs.tar
      - name: Ensure Identical Artifacts
        run: |
          sha256sum ${prefix}-rootfs.tar ${prefix}-orig.tar
          if ! diff ${prefix}-rootfs.tar ${prefix}-orig.tar; then
            sudo apt-get update
            sudo apt-get install --yes diffoscope
            diffoscope ${prefix}-rootfs.tar ${prefix}-orig.tar
          fi
  attestation:
    runs-on: ubuntu-latest
    needs:
      - timestamp
      - lint
      - bootstrap
      - bootstrap-offline
      - debootstrap
    permissions:
      id-token: write
      attestations: write
    steps:
      - uses: actions/download-artifact@v4
        with:
          path: artifacts
          merge-multiple: true
      - name: Attest
        uses: actions/attest-build-provenance@v1
        with:
          subject-path: artifacts/*
