name: test
on:
  push:
    branches:
      - "main"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build Docker image
        run: docker build . --tag bootstrap --file Containerfile
      - name: Run Docker container
        run: docker run --privileged bootstrap
