name: test
on:
  push:
    branches:
      - "main"
jobs:
  debootstrap:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-qemu-action@v3
      - name: Run Debootstrap
        run: |
          docker build --file Containerfile --target debootstrap --tag debootstrap .
          docker run --privileged --volume "$(pwd):/out" debootstrap
          sudo tar czf rootfs.tar.gz rootfs
          sudo chown $(id -u):$(id -g) rootfs.tar.gz
      - name: Archive Result
        uses: actions/upload-artifact@v4
        with:
          path: rootfs.tar.gz
          name: debootstrap.tar.gz
