name: test
on:
  push:
    branches:
      - "main"
jobs:
  debootstrap:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-qemu-action@v3
      - name: Run debootstrap
        run: |
          docker build --file Containerfile --target debootstrap --tag debootstrap .
          docker run --privileged --volume "$(pwd):/out" debootstrap
          sudo tar czf rootfs.tar.gz rootfs
          sudo chown $(id -u):$(id -g) rootfs.tar.gz
      - name: Archive Result
        uses: actions/upload-artifact@v4
        with:
          path: rootfs.tar.gz
          name: debootstrap.tar.gz
  pi-gen:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-qemu-action@v3
      - name: Run pi-gen
        run: |
          docker build --file Containerfile --target pi-gen --tag pi-gen .
          docker run --privileged --volume "$(pwd)/deploy:/pi-gen/deploy" pi-gen
          cp deploy/*.zip pi-gen.zip
      - name: Archive Result
        uses: actions/upload-artifact@v4
        with:
          path: pi-gen.zip
          name: pi-gen.zip
