name: Test Raspberry Pi Bootstrap
on:
  push:
    branches:
      - "main"
    paths:
      - bootstrap-rpi/**
      - .github/workflows/pi-gen.yml
jobs:
  bootstrap:
    runs-on: ubuntu-latest
    steps:
      - name: Get Repository
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Run Bootstrap
        run: |
          cd bootstrap-rpi
          docker build --file Containerfile --target bootstrap --tag bootstrap .
          docker run \
            --env keyserver=none \
            --privileged \
            --volume "$(pwd)/cache:/cache" \
            --volume "$(pwd):/deploy" \
            bootstrap
          tar --create --xz --file ../cache.tar.xz cache
      - name: Archive Image
        uses: actions/upload-artifact@v4
        with:
          path: raspios.img.xz
          name: raspios.img.xz
      - name: Archive Cache
        uses: actions/upload-artifact@v4
        with:
          path: cache.tar.xz
          name: cache.tar.xz
  pi-gen:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-qemu-action@v3
      - name: Run pi-gen
        run: |
          cd bootstrap-rpi
          docker build --file Containerfile --target pi-gen --tag pi-gen .
          docker run --privileged --volume "$(pwd)/deploy:/pi-gen/deploy" pi-gen
          cp deploy/*.xz ../pi-gen.xz
      - name: Archive Image
        uses: actions/upload-artifact@v4
        with:
          path: pi-gen.xz
